### ISSUE TITLE
Airpaces

### ISSUE THREAD

**Issue by mzoricic** [aixm/Donlon_2022#3]
- FIR, EAAD - f4d5e4d4-d84a-481f-b9e3-b359e42c0dff- Deserialization exception occured. Property Name: [upperLimit] Message: UOM not defined! 
- TMA_P, EAMM2 - 010d8451-d751-4abb-9c71-f48ad024045b - Deserialization exception occured. Property Name: [beginPosition] Message: The DateTime represented by the string is not supported in calendar System.Globalization.GregorianCalendar.

**Comment by porosnie** [comment]
issues corrected
